### ISSUE TITLE
error installing package

### ISSUE THREAD

**Issue by lisindima** [noppefoxwolf/RefreshUI#1]
<img width="730" alt="Снимок экрана 2019-11-08 в 15 25 42" src="https://user-images.githubusercontent.com/43087859/68461206-41981280-023c-11ea-8d9c-b9fd20d65f8b.png">

**Comment by noppefoxwolf** [comment]
@lisindima put your public key on your github or use https.

**Comment by lisindima** [comment]
Thanks!
